language: cpp
install:
  - sudo pip install cpp-coveralls
  - sudo pip install pytest
  - sudo pip install cffi
  - sudo apt-add-repository --yes ppa:ubuntu-toolchain-r/test
  - sudo apt-get update
  - sudo apt-get install gcc-4.9 g++-4.9 valgrind
script:
  - python setup.py --type=debug --coverage
  - cd build
  - make
  - make test
  - cd ..
  - pep8 --ignore=E501 test/test.py
  - py.test -vv test/test.py build
after_success:
  - coveralls -E ".*external.*" -E ".*CMakeFiles.*" -E ".*test/.*.cpp.*" -E ".*src/lebedev/.*.cpp.*"
