language: cpp

sudo: false

cache:
  ccache: true
  directories:
    - $HOME/.ccache

env:
  global:
    - USE_CCACHE=1
    - CCACHE_COMPRESS=1
    - CCACHE_MAXSIZE=200M
    - CCACHE_CPP2=1

matrix:
  include:

    # 1/ Linux Clang Builds
    - os: linux
      compiler: clang
      addons: &clang37
        apt:
          sources: ['llvm-toolchain-precise-3.7', 'ubuntu-toolchain-r-test']
          packages: ['clang-3.7', 'gfortran', 'python-virtualenv']
      env: CXX='clang++-3.7' CC='clang-3.7' FC='gfortran' BUILD_TYPE='release'

    - os: linux
      compiler: clang
      addons: *clang37
      env: CXX='clang++-3.7' CC='clang-3.7' FC='gfortran' BUILD_TYPE='debug'

    # 2/ Linux GCC Builds
    - os: linux
      compiler: gcc
      addons: &gcc5
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-5', 'gcc-5', 'gfortran-5', 'python-virtualenv']
      env: CXX='g++-5' CC='gcc-5' FC='gfortran-5' BUILD_TYPE='release'

    - os: linux
      compiler: gcc
      addons: *gcc5
      env: CXX='g++-5' CC='gcc-5' FC='gfortran-5' BUILD_TYPE='debug'

    # 3/ OSX Clang Builds
    - os: osx
      osx_image: xcode9.2
      compiler: clang
      env: CXX='clang++' CC='clang' FC='gfortran' BUILD_TYPE='debug'

    - os: osx
      osx_image: xcode9.2
      compiler: clang
      env: CXX='clang++' CC='clang' FC='gfortran' BUILD_TYPE='release'

    # 4/ OSX GCC5 Builds
    - os: osx
      osx_image: xcode9.2
      compiler: gcc
      env: CXX='g++' CC='gcc' FC='gfortran' BUILD_TYPE='debug'

    - os: osx
      osx_image: xcode9.2
      compiler: gcc
      env: CXX='g++' CC='gcc' FC='gfortran' BUILD_TYPE='release'

install:
  - DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
  - mkdir -p ${DEPS_DIR}
  - cd ${DEPS_DIR}
  - |
    if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
      cd ${TRAVIS_BUILD_DIR}
      curl https://cmake.org/files/v3.12/cmake-3.12.3-Linux-x86_64.tar.gz | tar xz
      export PATH=$PWD/cmake-3.12.3-Linux-x86_64/bin:$PATH
      export LD_LIBARY_PATH=$PWD/cmake-3.12.3-Linux-x86_64/lib:$LD_LIBRARY_PATH
      cd ${DEPS_DIR}
      curl -O https://www.python.org/ftp/python/3.6.6/Python-3.6.6.tgz
      tar xf Python-3.6.6.tgz
      cd Python-3.6.6
      ./configure --prefix=${DEPS_DIR}/python/
      make > /dev/null
      make install > /dev/null
      export PATH=${DEPS_DIR}/python/bin:$PATH
      export LD_LIBARY_PATH=${DEPS_DIR}/python/lib:$LD_LIBRARY_PATH
      pip install --user pipenv --upgrade
    elif [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then
      brew update &> /dev/null
      brew cask uninstall --force oclint
      brew upgrade python
      brew install gcc pipenv
      brew upgrade cmake
    fi

before_script:
  - cd ${TRAVIS_BUILD_DIR}
  - |
    if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
      pipenv install --python=python3
    elif [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then
      pipenv install --python=/usr/local/bin/python3
    fi
  - export PATH=$HOME/.local/bin:$PATH
  - |
    if [[ "${COVERAGE}" = true ]]; then
      ./setup --fc-support=ON --fc=$FC --cc=$CC --cxx=$CXX --type=${BUILD_TYPE} --coverage
    else
      ./setup --fc-support=ON --fc=$FC --cc=$CC --cxx=$CXX --type=${BUILD_TYPE}
    fi
  - cd build

script:
  - make -j 2
  - ctest -V -j 2
  - cd ..
  - pipenv run pycodestyle --ignore=E501 test/test.py
  - cd ${TRAVIS_BUILD_DIR}
  - mkdir test_python_interface
  - cp ${TRAVIS_BUILD_DIR}/test/test.py test_python_interface
  - cp ${TRAVIS_BUILD_DIR}/test/reference_grid/cc-pVDZ.txt test_python_interface
  - cd test_python_interface
  - |
    if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
      pipenv install ${TRAVIS_BUILD_DIR}
    elif [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then
      pipenv install --python=/usr/local/bin/python3 ${TRAVIS_BUILD_DIR}
      pipenv install --python=/usr/local/bin/python3 pytest
    fi
  - pipenv run pytest test.py

after_success:
  - cd ${TRAVIS_BUILD_DIR}/build
  - |
    if [[ "${COVERAGE}" = true ]]; then
      coveralls -E ".*external.*" -E ".*CMakeFiles.*" -E ".*test/.*.cpp.*" || echo 'coveralls upload failed.'
    fi

notifications:
  email: false
